name: Build Android APK
on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: |
          pip install flet==0.82.2 flet-audio==0.82.2
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Build APK
        run: |
          # The -y flag is critical to prevent the EOF error by auto-accepting SDKs
          python -m flet build apk -y --permissions READ_EXTERNAL_STORAGE
          
          
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NovaMusic-APK
          path: build/apk/*.apk
          
